src/gateway/node-vanilla-gateway.js
=> Add support for https on node

src/gateway/vanilla-gateway.js
=> fix header without comma

README.md, spec/browser/gateway/fetch-spec.js, spec/browser/gateway/xhr-spec.js, spec/browser/index.js, spec/browser/middlewares/basic-auth-spec.js, spec/browser/request-spec.js, spec/browser/utils-spec.js, spec/integration/server.js, spec/integration/shared-examples.js, spec/integration/support/manifest.js, spec/integration/support/responses.js, src/gateway/fetch.js, src/gateway/http.js, src/gateway/xhr.js, src/method-descriptor.js, src/middlewares/basic-auth.js, src/request.js, src/utils.js
=> Basic auth

README.md, spec/browser/middlewares/timeout-spec.js, spec/browser/request-spec.js, spec/integration/server.js, spec/integration/shared-examples.js, spec/integration/support/manifest.js, spec/integration/support/responses.js, src/gateway/fetch.js, src/gateway/http.js, src/gateway/xhr.js, src/method-descriptor.js, src/middlewares/timeout.js, src/request.js
=> Support timeout

src/index.js, src/utils.js
=> Better support for Strict mode.

spec/browser/utils-spec.js, src/utils.js
=> Remove modifying window object

package.json, scripts/ci.sh, spec/browser/gateway/fetch.spec.js, spec/browser/gateway/xhr.spec.js, spec/node/gateway/http.spec.js, src/middlewares/basic-auth.js, src/middlewares/timeout.js, src/response.js
=> Hide the auth password in the Response object

README.md, spec/browser/client-builder.spec.js, spec/browser/mappersmith.spec.js, spec/browser/middleware.spec.js, spec/helper.js, src/client-builder.js, src/manifest.js, src/mappersmith.js
=> Adds clientId and possibility to set global context

src/gateway/xhr.js
Paired with @oleggromov
Source: https://stackoverflow.com/a/34647690
=> Fix IE binary request by configuring responseType after open

src/gateway/xhr.js
See an issue and a fix in axios
https://github.com/axios/axios/issues/26
https://github.com/axios/axios/pull/30
=> method name should be uppercase

src/test.js
https://github.com/tulios/mappersmith/issues/84
=> Require index.js instead of mappersmith.js in test.js

spec/browser/gateway/fetch.spec.js, spec/browser/gateway/xhr.spec.js, spec/browser/middleware/retry/shared-examples.js, spec/node/gateway/http.spec.js, src/gateway/fetch.js, src/gateway/http.js, src/gateway/mock.js, src/gateway/xhr.js
As discussed on slack, some of the tests fail due to timeouts. Would be great if you could investigate that for me :-)
=> Add support for HEAD HTTP method

spec/browser/test/mock-resource.spec.js, src/mocks/mock-request.js, src/mocks/mock-resource.js
=> Set responseData and content type correctly over multiple mock requests

CHANGELOG.md, package.json, spec/browser/test/mock-resource.spec.js, spec/helper.js, src/mocks/mock-resource.js
Adds support for async middleware requests in mocked clients
=> add support for async middleware requests in mocked clients

README.md, spec/browser/global-middleware.spec.js, spec/browser/middleware.spec.js, src/manifest.js, src/method-descriptor.js
=> Resource middleware

README.md
Improving documentation as requested on issue #97.
=> Adding MockAssert information in README

spec/typescript/test.spec.ts, typings/test.d.ts
=> fix typings for mockRequest.url

spec/browser/request.spec.js, src/request.js
- Replacing multiple instances of same path parameter
- Regexp injection vulnerability
=> Fix issues #172 #173

spec/browser/response.spec.js, src/response.js
=> Preserve timeElapsed for Response#enhance

README.md, spec/browser/request.spec.js, src/method-descriptor.js, src/request.js
Addresses https://github.com/tulios/mappersmith/issues/159
=> Accept a function as MethodDescriptor.path

README.md, spec/browser/request.spec.js, src/manifest.js, src/method-descriptor.js, src/request.js
=> Require a flag to enable host override

README.md, spec/browser/test/mock-request.spec.js, src/test.js
=> add method for unusedMocks

README.md, spec/typescript/test.spec.ts, typings/test.d.ts
=> Fix missing type in `mockClient` interface

src/client-builder.ts
This will ensure the input structure for the client builders `build` method to construct resources based
on a manifest passed through forge.
=> Constraint generic build input type on client builder

CHANGELOG.md, spec/browser/test/mock-request.spec.js, src/mocks/mock-request.js
=> MockResource should match body by default

CHANGELOG.md, src/request.spec.ts, src/request.ts, src/types.ts, src/utils.ts
=> Fix path creation with object-ish params regression

CHANGELOG.md, spec/browser/test/mock-resource.spec.js, src/mocks/mock-request.js, src/utils/clone.spec.ts, src/utils/clone.ts, src/utils/index.spec.ts, src/utils/index.ts
=> Clone mock responses

CHANGELOG.md, src/middleware/basic-auth.ts, src/middleware/csrf.ts, src/middleware/duration.ts, src/middleware/encode-json.ts, src/middleware/global-error-handler.ts, src/middleware/index.ts, src/middleware/log.ts, src/middleware/retry/v2/index.ts, src/middleware/timeout.ts
=> Fix a typo that causes build problems in userland

CHANGELOG.md, README.md, src/index.d.ts, src/middleware/index.spec.ts, src/request.spec.ts, src/request.ts, src/test/request-factory.spec.js, src/test/request-factory.ts, src/test/response-factory.spec.ts
=> Add support for passing transient contexts between middleware

CHANGELOG.md, README.md, packages/core/src/client-builder.spec.ts, packages/core/src/client-builder.ts, packages/core/src/gateway.ts, packages/core/src/manifest.ts, packages/core/src/mappersmith.ts, packages/core/src/middleware/global-error-handler.ts, packages/test/src/index.js, packages/test/src/mocks/mock-resource.js
https://caniuse.com/?search=promise
=> [V3] Remove option to pass in custom Promise implementation

.changeset/polite-games-mix.md, CHANGELOG.md, package.json, src/version.ts
- Fixes `middlewares` import path #403
=> Prepare release 2.43.1

.changeset/clean-dragons-nail.md, CHANGELOG.md, package.json, src/version.ts
- 0b832ab: Fix ESM build to output correct code as per ESM spec
=> Prepare release 2.43.2

.changeset/empty-mirrors-fail.md, CHANGELOG.md, package.json, src/version.ts
- 404f7ba: Exporting client-builder
=> Prepare release 2.43.3

.changeset/fluffy-camels-approve.md, README.md, package.json, src/index.ts
Fixes https://github.com/tulios/mappersmith/issues/440
=> Deep exports

.changeset/fluffy-camels-approve.md, CHANGELOG.md, README.md, package.json, src/version.ts
- 7356e30: Expose deep imports for backwards compatibility
=> Prepare release 2.43.4
