src/gateway/jquery-gateway.js
src/gateway/node-vanilla-gateway.js

Hello, I was trying to make a custom "batch requests" createGateway function like https://github.com/tulios/mappersmith-cached-gateway, following the protocol described at https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch, requiring modifying the header `Content-Type` to `Content-Type: multipart/mixed;`. The function took a Gateway argument so it could be used on the browser and in node, but I've found the default gateways that come with mappersmith, on some occasions would deliberately override the headers I've specifically specified. It means it would prevent someone from specifying headers when they know what they're doing.
Also it looked like there was a typo with `this.opts.header` missing an `s` in `src/gateway/jquery-gateway.js`.
I don't know if this is a desirable …

made headers from options higher priority than built-in headers.

---

README.md
src/mapper.js
test/mapper-test.js

When passing options for the gateway implementation you can ommit the callback parameter.

Ommit the callback parameter when passing options to gateway

---

CHANGELOG.md

This makes changelog more consistent and fixes [parsing error](https://allmychanges.com/p/javascript/mappersmith/) at AllMyChanges.com.

Use the same header level for 0.13.2 in a changelog

---

README.md
package.json
spec/browser/middlewares/retry.spec.js
src/middleware/retry.js

Add a retry validation callback to the Retry Middleware so that the caller can decide if the request should be retried based on the failed response object.

Add a retry validation callback to the Retry Middleware

---

spec/browser/test/mock-resource.spec.js
src/client-builder.js
src/manifest.js

The way I fixed it doesn't require changes to the mock-resource, so I think it's optimal.

Fix issue when mocking clients with middleware that use context

---

.travis.yml
README.md
spec/browser/client-builder.spec.js
spec/browser/mappersmith.spec.js
spec/browser/middleware.spec.js
spec/browser/test/mock-resource.spec.js
src/client-builder.js

If the request phase returns a promise it will be chained as usual
Example:
```javascript
const MyMiddleware = () => ({
request(req) {
return Promise.resolve(req.enhance({ headers: { token: 'abc' } }))
}
})
```
@carlrygart @ticolucci

Support async middleware request phase

---

spec/browser/response.spec.js
spec/integration/browser/integration.spec.js
spec/integration/node/integration.spec.js
spec/integration/support/index.js
src/gateway.js
src/gateway/fetch.js
src/gateway/http.js
src/gateway/xhr.js
src/response.js

XHR can't provide useful information on network errors, but luckily, platforms like react-native or the fetch gateway can offer better granularity on what is happening. This PR  introduces a new method to the `Response` object to return the last error on the stack. As usual, the middleware can add more errors to the stack and improve the error traceability.
On the gateway side, `dispatchClientError (message, error)` now receives the error instance as a second argument.
This PR solves issue #98 and can improve custom gateway implementations
^ @oblador @wisko

Improve network errors handling

---

README.md
spec/browser/client-builder.spec.js
spec/helper.js
src/manifest.js

This fixes #56 
It allows setting of the bodyAttr param at manifest level so that it is not repeated for every resource if it is always different from 'body'

Allow setting of some resource configs at manifest level

---

package.json
spec/browser/gateway/fetch.spec.js
spec/browser/gateway/xhr.spec.js
spec/helper.js
spec/integration/shared-examples.js
spec/node/gateway/http.spec.js
src/middleware/retry/v2/index.js
yarn.lock

Update the RetryMiddleware so that if an earlier middleware in the chain throws then we don't get an unhandled promise rejection.

Update the RetryMiddleware to handle errors

---

spec/browser/request.spec.js
src/request.js

I will hold until my last breath that a query string is delimited by a single question mark, and that the query part is entirely opaque (https://tools.ietf.org/html/rfc3986#section-3.4), but since apparently some clients barf if you give them a query string containing multiple question marks instead of ampersands, here we are.

Fix invalid query string when path already contains query string

---

spec/browser/middleware.spec.js
spec/browser/test/mock-resource.spec.js
src/gateway/mock.js
src/mocks/mock-resource.js
yarn.lock

Fix a bug where `mockRequest` would attempt to run the old request phase without considering async definitions

Fix mockResource with async request phase

---

src/test.js

Mappersmith versions `2.27.0` and `2.27.1` might throw `ReferenceError: regeneratorRuntime is not defined` when importing the test library (`mappersmith/test`) on environments without a transpiler. There was an async function that is now replaced by a regular Promise.

Fix "ReferenceError: regeneratorRuntime is not defined"

---

typings/index.d.ts

`ignoreGlobalMiddleware` was missing in the type definition

Add `ignoreGlobalMiddleware` to types

---

typings/index.d.ts

In TypeScript 3.6 the global type `GlobalFetch` will be renamed, were it would need to be extracted in the following way: `WindowOrWorkerGlobalScope['fetch']`. While checking the interface `FetchGateway` it came up that the GlobalFetch does not need to be extended. So I removed it :)

remove in TypeScript 3.6 removed type GlobalFetch from FetchGateway

---

typings/middleware/retry.d.ts

Since the Retry middleware already assigns the default config when it's created with no parameters, that should be reflected in the Typescript definition files.

Allow not sending a config in the Retry middleware

---

README.md
spec/browser/request.spec.js
src/request.js

Support paths params like `/api/{market?}/users`, that would result in `/api/users` if the `market` parameter is missing in request.

Add support for optional path params (dynamic segments)

---

typings/test.d.ts

Fixes #157 
Using [`Option B` approach](https://github.com/tulios/mappersmith/issues/157#issuecomment-557803794):
```js
const mock = mockClient(github)
.resource("Status")
.method("current")
.with({ id: "abc" })
.response({ allUsers: [] })
.assertObject();
```
or, if you really want to change the order of applying `resource` and `method`:
```js
const mock = mockClient<typeof github, "Status">(github)
.resource("Status")
.method("current")
.with({ id: "abc" })
.response({ allUsers: [] })
.assertObject();
```

Fix types for MockClient

---

src/gateway/fetch.js

This pull request fixes "configs.gatewayConfigs.Fetch" not working.
According to the example this should now work 
```
configs.gatewayConfigs.Fetch = {
credentials: 'same-origin'
}
```

Fix fetch configs not working

---

spec/browser/request.spec.js
src/request.js

Thoughts:
- Should we **only** ignore `null` and `undefined` for *optional* dynamic segments? In that way we can keep the current behaviour for mandatory dynamic segments, which is to replace it with `undefined` or `null`.

Ignore null or undefined values for dynamic segments

---

src/gateway/http.js
src/mappersmith.js

Request Timeout to include DNS and Socket connection

---

spec/browser/test/mock-resource.spec.js
src/mocks/mock-resource.js

My brain hurts after this debug session 🤕😂 
This PR fixes a bug (or at least I think it is a bug) that happens when using mocks with param-matcher functions. The bug is that if a mock contains at least one param-matcher function, then all params provided in `.with()` will be replaced in the "evaluation" of the param-matchers. 
A bit hard to explain (I'm a bad writer), but I think the test in this PR shows the bug quite well.

Fix so only param matchers are changed for mocks

---

typings/middleware/encode-json.d.ts

The exported constant `CONTENT_TYPE_JSON` (from middleware/json-encode) was missing from the type declaration.

Add json-encode middleware export CONTENT_TYPE_JSON to type definition

---

spec/typescript/basic.spec.ts
typings/index.d.ts

In https://github.com/kafkajs/confluent-schema-registry/pull/108 we want to configure the gateway for one specific client, instead of modifying it globally. This is possible in JS, but the Typescript types were missing the `gatewayConfigs` property on the `Options` passed to forge.

Update types to allow passing gatewayConfigs to forge options

---

spec/browser/response.spec.js
src/response.js

When enhancing responses, if the enhancement does not include error, it is not pushed into the errors stack
Fixes https://github.com/tulios/mappersmith/issues/230

Prevents pushing undefined values into Response errors stack on enhance

---

spec/browser/response.spec.js
src/response.js

Expands the REGEXP_CONTENT_TYPE_JSON regex to recognise more Json content type flavours.
Fixes https://github.com/tulios/mappersmith/issues/223

Expands the Json content type regexp to accommodate more Json content types

---

CHANGELOG.md
typings/index.d.ts

Recently (22f6a16c7329bb51341ffd09b0997a34b629fbb0) the v2 retry middleware was moved out of the primary `retry.d.ts` file into its own.  It appears that this new file needs to be added to the list of triple-slash directives that cause the typescript compiler to include various files that are not explicitly imported.
Without this, I get a compiler error on a module that indirectly (via `@kafkajs/confluent-schema-registry`) uses mappersmith:
```
Could not find a declaration file for module 'mappersmith/middleware/retry/v2'.  '/path/to/my/module/node_modules/mappersmith/middleware/retry/v2/index.js' implicitly has an 'any' type.
If the 'mappersmith' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module …
```

Add missing "triple-slash directive" for new typings file

---

CHANGELOG.md
spec/typescript/middleware.spec.ts
spec/typescript/response.spec.ts
src/client-builder.spec.ts
src/gateway/types.ts
src/manifest.ts
src/mappersmith.js
src/response.spec.ts
src/response.ts
src/test.js
src/test.spec.js
typings/generated/src/gateway/types.d.ts
typings/generated/src/manifest.d.ts
typings/generated/src/response.d.ts
typings/index.d.ts
typings/test.d.ts

Improves the developer ergonomics of typing client responses: #263 
The generic defaults to `ParsedJSON`

Make Response class accept a generic of it's returned data type

---

CHANGELOG.md
spec/browser/test/mock-request.spec.js
src/utils/clone.spec.ts
src/utils/clone.ts

Fix: Allow `Buffer` (and similar) as valid response data for `mockRequest`

---

.babelrc.js
CHANGELOG.md

Ensure references to `regeneratorRuntime` is not part of compiled bundle

---

CHANGELOG.md
spec/browser/test/mock-request.spec.js
spec/ts-helper.ts
src/request.ts

Properly merge headers when one of the sides is a mock matcher

---

CHANGELOG.md
src/middleware/retry/v2/index.ts
src/response.ts

- This was typed like this to be compatible with RetryMiddleware
- RetryMiddlewareV2 will no longer have Response in it. Although this is a "breaking" change, I don't think it's a big deal as A) it's a built in middleware that is opt-in (should be its own package tbh) and B) people can still push to it if they cast it as any.

Response.errors should not be allowed an instance of Response

---

CHANGELOG.md
README.md
src/method-descriptor.ts
src/request.spec.ts
src/request.ts
src/types.ts

In a project we are looking at we are trying to create a dynamic mappersmith client we are relying on overriding `host` with `$hostname$path`:
```ts
const client = forge({
clientId: name,
host,  // https://api.ourdomain.com/dcom/financialoptions/configuration
middleware: [...middleware, ...baseMiddleware],
resources, // resources is a dummy that has path: ''
allowResourceHostOverride: true,
}) as unknown as Resources;
```
There are two problems with this:
1) Mappersmith expects `host` to be only host. This is fine, but it also pushes the responsiblity of `/` between host and `path` to `path` when it is part of neither: https://www.rfc-editor.org/rfc/rfc1738#section-3.1 which is an internal mappersmith design decision that has worked out fine so far (even though it might not be 100% …

Allow path to be set by Request.enhance

---

CHANGELOG.md
spec/typescript/basic.spec.ts
src/client-builder.spec.ts
src/client-builder.ts
src/request.spec.ts

Fixes #330 
Usage:
```ts
github.Status.lastMessage(
{ randomParam: 10, another: { foo: 'hi' } },
{ myContext: 'something ' }
).then((response) => {
const context = response.originalRequest.context<{ myContext: string }>()
console.log({ myContext: context.myContext })
})
```
The context is meant to be used for request/response middleware to carry information from one middleware to another, or in this case, from the caller to to the middleware.
Passing a context is optional, and doing so will **not** affect the final request that is sent over the wire in **any way**, so it is safe to start using it, and knowing it won't mutate any Gateway IO.

Allow Client invocations to specify RequestContext

---

CHANGELOG.md
README.md
spec/browser/middleware.spec.js
spec/typescript/middleware.spec.ts
src/client-builder.ts
src/middleware/duration.spec.ts
src/middleware/global-error-handler.spec.ts
src/middleware/index.spec.ts
src/middleware/index.ts

Fixes #321 
Usage:
```ts
return function MyMiddleware() {
return {
async response(next, _, request) {
// Access the final request object without invoking `await next()`:
const context = request.context<{ host: string }>();
```

Add support for final request in response phase

---

CHANGELOG.md
packages/core/src/gateway.ts
packages/core/src/middleware/basic-auth.spec.ts
packages/core/src/middleware/csrf.web.spec.ts
packages/core/src/middleware/duration.spec.ts
packages/core/src/middleware/encode-json.spec.ts
packages/core/src/middleware/encode-json.ts
packages/core/src/middleware/global-error-handler.spec.ts
packages/core/src/middleware/retry.web.spec.ts
packages/core/src/middleware/timeout.spec.ts
packages/core/src/request.ts
packages/test/src/index.js
packages/test/src/mocks/mock-request.js
packages/test/src/mocks/mock-resource.js

`Request.prototype.body` now respects `content-type` header and returns a JSON parsed result if the `content-type` is in the `+json` family. If you want the raw body without transformation, use `Request.prototype.rawBody` instead.
Fixes #343

[V3] `Request.prototype.body` now respects `content-type` header

---

.changeset/beige-rice-kick.md
CHANGELOG.md
README.md
package.json
scripts/release.sh

Versioning, changelog and publishing is now done via Changesets. Update README accordingly.

Change how releases are done

---

.changeset/spotty-steaks-hide.md
src/test/index.d.ts

Fixes #393 
Added missing type declarations for exported unusedMocks test function

Fix: missing types for unusedMocks

---

.changeset/friendly-bottles-unite.md
spec/integration/node/integration.spec.js
spec/integration/node/support/keep-alive.js
src/gateway/http.ts

Fixes #390 
This pull request contains:
- [The spec](https://github.com/tulios/mappersmith/pull/391/files#diff-f7285d0cc47d59dcea7a2d0488dbdee625f914ff697b5bd9b574b8e160758545R91-R98) to reproduce the memory leak condition and the fix
- Inverted logic for the [sockets related event listener assignments](https://github.com/tulios/mappersmith/pull/391/files#diff-97d4b84b631227c34c616f2edd0036181c063f4d022e56009ecba4b3e171f8c2R104-R106). The event listeners only register if the specific hook is defined in the HTTP gatewayConfig object.
The spec fails without the fix: when keep-alive is enabled, the tcp socket events register twice (once per API call):
> [test] 1) integration HTTP event callbacks keep alive
[test]   Message:
[test]     Expected 2 to be 1.
[test]   Stack:
[test]         at …

Fix: memory leak with when using Http(s)Agent keepAlive=true

---

.changeset/dirty-years-sparkle.md
.changeset/friendly-bottles-unite.md
.changeset/spotty-steaks-hide.md
CHANGELOG.md
README.md
package.json
src/version.ts

- 6e94f97: Bundle with ESM exports.
- The recommended way to use mappersmith in ESM projects is to do `import { forge } from 'mappersmith'` rather than the old `import forge from 'mappersmith'`. The reason is because test runners like jest and vitest might get confused when mixing named/default exports together with ESM, even though tsc and node has no problems with it.
- A similar recommendation change goes for importing middleware: do `import { EncodeJsonMiddleware } from 'mappersmith/middleware'` (note the `mappersmith/middleware` folder) rather than deep import `import EncodeJsonMiddleware from 'mappersmith/middleware/encode-json'`. We still support the old import, but it will be deprecated in the future.
- The same recommendation goes for importing gateway: do `import { FetchGateway …

Prepare release 2.43.0

---

.github/actions/setup-environment/action.yml
.github/actions/setup-smoke-test/action.yml
.github/workflows/smoke.js.yml

Fixes #408 
This PR smoke tests a release to ensure the npm artefact is ready for release. The steps are roughly:
1. Clone repo, install deps
2. Prepare a mappersmith release
3. Clone https://github.com/klippx/mappersmith-consumer repo 
4. In `mappersmith-consumer`: Link to the release candidate
5. In `mappersmith-consumer`: Run all test scripts verifying that they run with release candidate
- This ensures that consumer projects are not broken*
- If there is a missed case it is easy to add to that as a new workspace consumer project
- No impact on this project in terms of deps
*) to the extent that we know about it and that it is documented, of course

Smoke test release candidate

---

.changeset/empty-mirrors-fail.md
package.json
src/index.ts

Since version 2.43.0 the imports are broken for 'mappersmith/client-builder', everything else is exported from index.ts, except for `ClientBuilder` class

Export ClientBuilder from index.ts

---

.changeset/sharp-vans-approve.md
README.md
spec/integration/browser/integration.spec.js
spec/integration/node/integration.spec.js
src/client-builder.spec.ts
src/gateway/fetch.ts
src/gateway/http.ts
src/gateway/xhr.ts
src/manifest.ts
src/method-descriptor.ts
src/request.spec.ts
src/request.ts
src/types.ts

https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal
It is standard practice for all APIs capable of using the AbortController API to take the signal property of an AbortController class instance as an argument. In Mappersmith case, we are the glue between the user and Fetch / HTTP and these APIs support AbortController API. Let's get out of the way and let people use it if they need.

Add support for AbortSignal

---

src/gateway/http.ts

- Switch to using default imports for libraries imported in gateway
- Default imports (import http) create a direct reference to the module exports
- Named imports and namespace imports (import * as) create a new reference that won't reflect patches
We have a use case where we patch methods exposed by `node:http` and `node:https` globally in a node.js application. This affects applications compiled using ESM. CJS application are unaffected. Tested this change and this doesn't affect any existing applications using mappersmith.

Use non-wildcard imports in mappersmith gateway

---

.changeset/five-squids-sip.md
CHANGELOG.md
package.json
src/version.ts

- 624c15d: Switch to using default imports for libraries imported in gateway

Prepare release 2.45.0

---

.changeset/silent-paws-itch.md
spec/integration/node/integration.spec.js
src/gateway/fetch.ts

When using node's native Fetch or even `node-fetch` fetch, we need to relay the timeout via `signal` to the library to allow it to actually cancel the request on the wire instead of leaving it hanging

Abort request for Fetch after Timeout reached
